### ISSUE TITLE
TOC建议

### ISSUE THREAD

**Issue by istek** [firekylin/firekylin#362]
目前TOC是在正文最前面，有时候文章长点，想点其他章节看的话，不方便。

建议将TOC的内容这个DIV浮动到页面右侧，随页面上下滚动而滚动，为了防止阻挡阅读正文，可以增加一个按钮，来显示或者隐藏这个DIV。

**Comment by lizheming** [comment]
`外观设置->主题管理` 里面可以自定义 CSS，这些可以自行实现~

**Comment by xuexb** [comment]
赞, 我之前也想做让TOC悬浮在右上角, 可以使用js+sticky实现, 如: <https://xuexb.com/post/273.html?sid=10> , 后台简单设置的css:

```css
@media screen and (min-width: 769px) {
    .toc {
        float: right;
        position: sticky;
        top: 0;
        z-index: 1000;
        background-color: rgba(255, 255, 255, .8);
        border: 1px solid #ccc;
        padding: 0 10px;
    }
}
```
